using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace EstherMod.Common.Extensions;

public static class SpriteBatchExtensions {
	private static Snapshot TakeSnapshot(this SpriteBatch spriteBatch) => new(spriteBatch);
	private static void Begin(this SpriteBatch spriteBatch, Snapshot snapshot) {
		spriteBatch.Begin(snapshot.sortMode, snapshot.blendState, snapshot.samplerState, snapshot.depthStencilState, snapshot.rasterizerState, snapshot.effect, snapshot.transformationMatrix);
	}

	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, samplerState = samplerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, BlendState blendState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, blendState = blendState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, SamplerState samplerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, samplerState = samplerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SpriteSortMode sortMode, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { sortMode = sortMode, transformationMatrix = transformationMatrix });

	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, SamplerState samplerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, samplerState = samplerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, BlendState blendState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { blendState = blendState, transformationMatrix = transformationMatrix });

	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, SamplerState samplerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { samplerState = samplerState, transformationMatrix = transformationMatrix });

	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState });
	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState, rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState, rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState, rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, DepthStencilState depthStencilState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { depthStencilState = depthStencilState, transformationMatrix = transformationMatrix });

	public static void BeginWith(this SpriteBatch spriteBatch, RasterizerState rasterizerState) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { rasterizerState = rasterizerState });
	public static void BeginWith(this SpriteBatch spriteBatch, RasterizerState rasterizerState, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { rasterizerState = rasterizerState, effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, RasterizerState rasterizerState, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { rasterizerState = rasterizerState, effect = effect, transformationMatrix = transformationMatrix });
	public static void BeginWith(this SpriteBatch spriteBatch, RasterizerState rasterizerState, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { rasterizerState = rasterizerState, transformationMatrix = transformationMatrix });

	public static void BeginWith(this SpriteBatch spriteBatch, Effect effect) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { effect = effect });
	public static void BeginWith(this SpriteBatch spriteBatch, Effect effect, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { effect = effect, transformationMatrix = transformationMatrix });

	public static void BeginWith(this SpriteBatch spriteBatch, Matrix transformationMatrix) => spriteBatch.Begin(spriteBatch.TakeSnapshot() with { transformationMatrix = transformationMatrix });

	private struct Snapshot {
		public SpriteSortMode sortMode;
		public BlendState blendState;
		public SamplerState samplerState;
		public DepthStencilState depthStencilState;
		public RasterizerState rasterizerState;
		public Effect effect;
		public Matrix transformationMatrix;

		public Snapshot(SpriteBatch spriteBatch) {
			sortMode = spriteBatch.sortMode;
			blendState = spriteBatch.blendState;
			samplerState = spriteBatch.samplerState;
			depthStencilState = spriteBatch.depthStencilState;
			rasterizerState = spriteBatch.rasterizerState;
			effect = spriteBatch.customEffect;
			transformationMatrix = spriteBatch.transformMatrix;
		}
	}
}
